// Code generated by protoc-gen-go.
// source: xdrive_data.proto
// DO NOT EDIT!

/*
Package xdrive is a generated protocol buffer package.

It is generated from these files:
	xdrive_data.proto

It has these top-level messages:
	ColumnDesc
	Filter
	CSVSpec
	FileSpec
	StringList
	KeyValue
	KeyValueList
	RmgrInfo
	ReadRequest
	SampleRequest
	DataReply
	XCol
	XRowSet
	PluginDataReply
	SizeMetaRequest
	SizeMetaReply
	PluginSizeMetaReply
	WriteRequest
	PluginWriteRequest
	WriteReply
	PluginWriteReply
	XMsg
*/
package xdrive

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SpqType int32

const (
	SpqType_UNKNOWN SpqType = 0
	SpqType_BOOL    SpqType = 1
	SpqType_INT16   SpqType = 2
	SpqType_INT32   SpqType = 3
	SpqType_INT64   SpqType = 4
	SpqType_INT128  SpqType = 5
	SpqType_FLOAT   SpqType = 6
	SpqType_DOUBLE  SpqType = 7
	// BYTEA    = 0x0008;   not supported.
	SpqType_CSTR             SpqType = 9
	SpqType_DEC64            SpqType = 10
	SpqType_DEC128           SpqType = 11
	SpqType_DATE             SpqType = 65539
	SpqType_TIME_MILLIS      SpqType = 131075
	SpqType_TIMESTAMP_MILLIS SpqType = 196612
	SpqType_TIME_MICROS      SpqType = 262148
	SpqType_TIMESTAMP_MICROS SpqType = 327684
	SpqType_JSON             SpqType = 393225
)

var SpqType_name = map[int32]string{
	0:      "UNKNOWN",
	1:      "BOOL",
	2:      "INT16",
	3:      "INT32",
	4:      "INT64",
	5:      "INT128",
	6:      "FLOAT",
	7:      "DOUBLE",
	9:      "CSTR",
	10:     "DEC64",
	11:     "DEC128",
	65539:  "DATE",
	131075: "TIME_MILLIS",
	196612: "TIMESTAMP_MILLIS",
	262148: "TIME_MICROS",
	327684: "TIMESTAMP_MICROS",
	393225: "JSON",
}
var SpqType_value = map[string]int32{
	"UNKNOWN":          0,
	"BOOL":             1,
	"INT16":            2,
	"INT32":            3,
	"INT64":            4,
	"INT128":           5,
	"FLOAT":            6,
	"DOUBLE":           7,
	"CSTR":             9,
	"DEC64":            10,
	"DEC128":           11,
	"DATE":             65539,
	"TIME_MILLIS":      131075,
	"TIMESTAMP_MILLIS": 196612,
	"TIME_MICROS":      262148,
	"TIMESTAMP_MICROS": 327684,
	"JSON":             393225,
}

func (x SpqType) String() string {
	return proto.EnumName(SpqType_name, int32(x))
}
func (SpqType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type XMsg_XMsgFlag int32

const (
	XMsg_EOS      XMsg_XMsgFlag = 0
	XMsg_EOB      XMsg_XMsgFlag = 1
	XMsg_CONTINUE XMsg_XMsgFlag = 2
	XMsg_SYNC     XMsg_XMsgFlag = 1000
	XMsg_BSPSYNC  XMsg_XMsgFlag = 1001
	XMsg_BSPDATA  XMsg_XMsgFlag = 1002
)

var XMsg_XMsgFlag_name = map[int32]string{
	0:    "EOS",
	1:    "EOB",
	2:    "CONTINUE",
	1000: "SYNC",
	1001: "BSPSYNC",
	1002: "BSPDATA",
}
var XMsg_XMsgFlag_value = map[string]int32{
	"EOS":      0,
	"EOB":      1,
	"CONTINUE": 2,
	"SYNC":     1000,
	"BSPSYNC":  1001,
	"BSPDATA":  1002,
}

func (x XMsg_XMsgFlag) String() string {
	return proto.EnumName(XMsg_XMsgFlag_name, int32(x))
}
func (XMsg_XMsgFlag) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{21, 0} }

type ColumnDesc struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Type int32  `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
}

func (m *ColumnDesc) Reset()                    { *m = ColumnDesc{} }
func (m *ColumnDesc) String() string            { return proto.CompactTextString(m) }
func (*ColumnDesc) ProtoMessage()               {}
func (*ColumnDesc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ColumnDesc) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ColumnDesc) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type Filter struct {
	Op     string   `protobuf:"bytes,1,opt,name=op" json:"op,omitempty"`
	Column string   `protobuf:"bytes,2,opt,name=column" json:"column,omitempty"`
	Args   []string `protobuf:"bytes,3,rep,name=args" json:"args,omitempty"`
}

func (m *Filter) Reset()                    { *m = Filter{} }
func (m *Filter) String() string            { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()               {}
func (*Filter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Filter) GetOp() string {
	if m != nil {
		return m.Op
	}
	return ""
}

func (m *Filter) GetColumn() string {
	if m != nil {
		return m.Column
	}
	return ""
}

func (m *Filter) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

type CSVSpec struct {
	Delimiter string `protobuf:"bytes,1,opt,name=delimiter" json:"delimiter,omitempty"`
	Nullstr   string `protobuf:"bytes,2,opt,name=nullstr" json:"nullstr,omitempty"`
	Header    bool   `protobuf:"varint,3,opt,name=header" json:"header,omitempty"`
	Quote     string `protobuf:"bytes,4,opt,name=quote" json:"quote,omitempty"`
	Escape    string `protobuf:"bytes,5,opt,name=escape" json:"escape,omitempty"`
}

func (m *CSVSpec) Reset()                    { *m = CSVSpec{} }
func (m *CSVSpec) String() string            { return proto.CompactTextString(m) }
func (*CSVSpec) ProtoMessage()               {}
func (*CSVSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CSVSpec) GetDelimiter() string {
	if m != nil {
		return m.Delimiter
	}
	return ""
}

func (m *CSVSpec) GetNullstr() string {
	if m != nil {
		return m.Nullstr
	}
	return ""
}

func (m *CSVSpec) GetHeader() bool {
	if m != nil {
		return m.Header
	}
	return false
}

func (m *CSVSpec) GetQuote() string {
	if m != nil {
		return m.Quote
	}
	return ""
}

func (m *CSVSpec) GetEscape() string {
	if m != nil {
		return m.Escape
	}
	return ""
}

type FileSpec struct {
	Path    string   `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Format  string   `protobuf:"bytes,2,opt,name=format" json:"format,omitempty"`
	Csvspec *CSVSpec `protobuf:"bytes,3,opt,name=csvspec" json:"csvspec,omitempty"`
}

func (m *FileSpec) Reset()                    { *m = FileSpec{} }
func (m *FileSpec) String() string            { return proto.CompactTextString(m) }
func (*FileSpec) ProtoMessage()               {}
func (*FileSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FileSpec) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *FileSpec) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *FileSpec) GetCsvspec() *CSVSpec {
	if m != nil {
		return m.Csvspec
	}
	return nil
}

type StringList struct {
	Str []string `protobuf:"bytes,1,rep,name=str" json:"str,omitempty"`
}

func (m *StringList) Reset()                    { *m = StringList{} }
func (m *StringList) String() string            { return proto.CompactTextString(m) }
func (*StringList) ProtoMessage()               {}
func (*StringList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *StringList) GetStr() []string {
	if m != nil {
		return m.Str
	}
	return nil
}

type KeyValue struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *KeyValue) Reset()                    { *m = KeyValue{} }
func (m *KeyValue) String() string            { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()               {}
func (*KeyValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *KeyValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type KeyValueList struct {
	Kv []*KeyValue `protobuf:"bytes,1,rep,name=kv" json:"kv,omitempty"`
}

func (m *KeyValueList) Reset()                    { *m = KeyValueList{} }
func (m *KeyValueList) String() string            { return proto.CompactTextString(m) }
func (*KeyValueList) ProtoMessage()               {}
func (*KeyValueList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *KeyValueList) GetKv() []*KeyValue {
	if m != nil {
		return m.Kv
	}
	return nil
}

type RmgrInfo struct {
	Scheme   string        `protobuf:"bytes,1,opt,name=scheme" json:"scheme,omitempty"`
	Format   string        `protobuf:"bytes,2,opt,name=format" json:"format,omitempty"`
	Rpath    string        `protobuf:"bytes,3,opt,name=rpath" json:"rpath,omitempty"`
	Conf     *KeyValueList `protobuf:"bytes,4,opt,name=conf" json:"conf,omitempty"`
	Pluginop string        `protobuf:"bytes,5,opt,name=pluginop" json:"pluginop,omitempty"`
	FragId   int32         `protobuf:"varint,6,opt,name=frag_id,json=fragId" json:"frag_id,omitempty"`
	FragCnt  int32         `protobuf:"varint,7,opt,name=frag_cnt,json=fragCnt" json:"frag_cnt,omitempty"`
}

func (m *RmgrInfo) Reset()                    { *m = RmgrInfo{} }
func (m *RmgrInfo) String() string            { return proto.CompactTextString(m) }
func (*RmgrInfo) ProtoMessage()               {}
func (*RmgrInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *RmgrInfo) GetScheme() string {
	if m != nil {
		return m.Scheme
	}
	return ""
}

func (m *RmgrInfo) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *RmgrInfo) GetRpath() string {
	if m != nil {
		return m.Rpath
	}
	return ""
}

func (m *RmgrInfo) GetConf() *KeyValueList {
	if m != nil {
		return m.Conf
	}
	return nil
}

func (m *RmgrInfo) GetPluginop() string {
	if m != nil {
		return m.Pluginop
	}
	return ""
}

func (m *RmgrInfo) GetFragId() int32 {
	if m != nil {
		return m.FragId
	}
	return 0
}

func (m *RmgrInfo) GetFragCnt() int32 {
	if m != nil {
		return m.FragCnt
	}
	return 0
}

type ReadRequest struct {
	// Which file(s)
	Filespec *FileSpec `protobuf:"bytes,1,opt,name=filespec" json:"filespec,omitempty"`
	// Table Schema
	Columndesc []*ColumnDesc `protobuf:"bytes,2,rep,name=columndesc" json:"columndesc,omitempty"`
	// Names of required columns
	Columnlist []string `protobuf:"bytes,3,rep,name=columnlist" json:"columnlist,omitempty"`
	// Filters
	Filter []*Filter `protobuf:"bytes,4,rep,name=filter" json:"filter,omitempty"`
	// Fragment
	FragId  int32 `protobuf:"varint,5,opt,name=frag_id,json=fragId" json:"frag_id,omitempty"`
	FragCnt int32 `protobuf:"varint,6,opt,name=frag_cnt,json=fragCnt" json:"frag_cnt,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ReadRequest) GetFilespec() *FileSpec {
	if m != nil {
		return m.Filespec
	}
	return nil
}

func (m *ReadRequest) GetColumndesc() []*ColumnDesc {
	if m != nil {
		return m.Columndesc
	}
	return nil
}

func (m *ReadRequest) GetColumnlist() []string {
	if m != nil {
		return m.Columnlist
	}
	return nil
}

func (m *ReadRequest) GetFilter() []*Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ReadRequest) GetFragId() int32 {
	if m != nil {
		return m.FragId
	}
	return 0
}

func (m *ReadRequest) GetFragCnt() int32 {
	if m != nil {
		return m.FragCnt
	}
	return 0
}

type SampleRequest struct {
	// Which file(s)
	Filespec *FileSpec `protobuf:"bytes,1,opt,name=filespec" json:"filespec,omitempty"`
	// Table Schema
	Columndesc []*ColumnDesc `protobuf:"bytes,2,rep,name=columndesc" json:"columndesc,omitempty"`
	// Fragment
	FragId  int32 `protobuf:"varint,3,opt,name=frag_id,json=fragId" json:"frag_id,omitempty"`
	FragCnt int32 `protobuf:"varint,4,opt,name=frag_cnt,json=fragCnt" json:"frag_cnt,omitempty"`
	// Sample size
	Nrow int32 `protobuf:"varint,5,opt,name=nrow" json:"nrow,omitempty"`
}

func (m *SampleRequest) Reset()                    { *m = SampleRequest{} }
func (m *SampleRequest) String() string            { return proto.CompactTextString(m) }
func (*SampleRequest) ProtoMessage()               {}
func (*SampleRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *SampleRequest) GetFilespec() *FileSpec {
	if m != nil {
		return m.Filespec
	}
	return nil
}

func (m *SampleRequest) GetColumndesc() []*ColumnDesc {
	if m != nil {
		return m.Columndesc
	}
	return nil
}

func (m *SampleRequest) GetFragId() int32 {
	if m != nil {
		return m.FragId
	}
	return 0
}

func (m *SampleRequest) GetFragCnt() int32 {
	if m != nil {
		return m.FragCnt
	}
	return 0
}

func (m *SampleRequest) GetNrow() int32 {
	if m != nil {
		return m.Nrow
	}
	return 0
}

type DataReply struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *DataReply) Reset()                    { *m = DataReply{} }
func (m *DataReply) String() string            { return proto.CompactTextString(m) }
func (*DataReply) ProtoMessage()               {}
func (*DataReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *DataReply) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type XCol struct {
	Colname string    `protobuf:"bytes,1,opt,name=colname" json:"colname,omitempty"`
	Nrow    int32     `protobuf:"varint,2,opt,name=nrow" json:"nrow,omitempty"`
	Nullmap []bool    `protobuf:"varint,3,rep,packed,name=nullmap" json:"nullmap,omitempty"`
	Sdata   []string  `protobuf:"bytes,4,rep,name=sdata" json:"sdata,omitempty"`
	I32Data []int32   `protobuf:"varint,5,rep,packed,name=i32data" json:"i32data,omitempty"`
	I64Data []int64   `protobuf:"varint,6,rep,packed,name=i64data" json:"i64data,omitempty"`
	F32Data []float32 `protobuf:"fixed32,7,rep,packed,name=f32data" json:"f32data,omitempty"`
	F64Data []float64 `protobuf:"fixed64,8,rep,packed,name=f64data" json:"f64data,omitempty"`
}

func (m *XCol) Reset()                    { *m = XCol{} }
func (m *XCol) String() string            { return proto.CompactTextString(m) }
func (*XCol) ProtoMessage()               {}
func (*XCol) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *XCol) GetColname() string {
	if m != nil {
		return m.Colname
	}
	return ""
}

func (m *XCol) GetNrow() int32 {
	if m != nil {
		return m.Nrow
	}
	return 0
}

func (m *XCol) GetNullmap() []bool {
	if m != nil {
		return m.Nullmap
	}
	return nil
}

func (m *XCol) GetSdata() []string {
	if m != nil {
		return m.Sdata
	}
	return nil
}

func (m *XCol) GetI32Data() []int32 {
	if m != nil {
		return m.I32Data
	}
	return nil
}

func (m *XCol) GetI64Data() []int64 {
	if m != nil {
		return m.I64Data
	}
	return nil
}

func (m *XCol) GetF32Data() []float32 {
	if m != nil {
		return m.F32Data
	}
	return nil
}

func (m *XCol) GetF64Data() []float64 {
	if m != nil {
		return m.F64Data
	}
	return nil
}

type XRowSet struct {
	Tag     int32   `protobuf:"varint,1,opt,name=tag" json:"tag,omitempty"`
	Round   int32   `protobuf:"varint,2,opt,name=round" json:"round,omitempty"`
	Columns []*XCol `protobuf:"bytes,3,rep,name=columns" json:"columns,omitempty"`
}

func (m *XRowSet) Reset()                    { *m = XRowSet{} }
func (m *XRowSet) String() string            { return proto.CompactTextString(m) }
func (*XRowSet) ProtoMessage()               {}
func (*XRowSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *XRowSet) GetTag() int32 {
	if m != nil {
		return m.Tag
	}
	return 0
}

func (m *XRowSet) GetRound() int32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *XRowSet) GetColumns() []*XCol {
	if m != nil {
		return m.Columns
	}
	return nil
}

type PluginDataReply struct {
	Errcode int32    `protobuf:"varint,1,opt,name=errcode" json:"errcode,omitempty"`
	Errmsg  string   `protobuf:"bytes,2,opt,name=errmsg" json:"errmsg,omitempty"`
	Rowset  *XRowSet `protobuf:"bytes,3,opt,name=rowset" json:"rowset,omitempty"`
}

func (m *PluginDataReply) Reset()                    { *m = PluginDataReply{} }
func (m *PluginDataReply) String() string            { return proto.CompactTextString(m) }
func (*PluginDataReply) ProtoMessage()               {}
func (*PluginDataReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *PluginDataReply) GetErrcode() int32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *PluginDataReply) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *PluginDataReply) GetRowset() *XRowSet {
	if m != nil {
		return m.Rowset
	}
	return nil
}

type SizeMetaRequest struct {
	// Which file(s)
	Filespec *FileSpec `protobuf:"bytes,1,opt,name=filespec" json:"filespec,omitempty"`
	// Table Schema
	Columndesc []*ColumnDesc `protobuf:"bytes,2,rep,name=columndesc" json:"columndesc,omitempty"`
	// Fragment
	FragId  int32 `protobuf:"varint,3,opt,name=frag_id,json=fragId" json:"frag_id,omitempty"`
	FragCnt int32 `protobuf:"varint,4,opt,name=frag_cnt,json=fragCnt" json:"frag_cnt,omitempty"`
}

func (m *SizeMetaRequest) Reset()                    { *m = SizeMetaRequest{} }
func (m *SizeMetaRequest) String() string            { return proto.CompactTextString(m) }
func (*SizeMetaRequest) ProtoMessage()               {}
func (*SizeMetaRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *SizeMetaRequest) GetFilespec() *FileSpec {
	if m != nil {
		return m.Filespec
	}
	return nil
}

func (m *SizeMetaRequest) GetColumndesc() []*ColumnDesc {
	if m != nil {
		return m.Columndesc
	}
	return nil
}

func (m *SizeMetaRequest) GetFragId() int32 {
	if m != nil {
		return m.FragId
	}
	return 0
}

func (m *SizeMetaRequest) GetFragCnt() int32 {
	if m != nil {
		return m.FragCnt
	}
	return 0
}

type SizeMetaReply struct {
	Nrow  int64 `protobuf:"varint,1,opt,name=nrow" json:"nrow,omitempty"`
	Nbyte int64 `protobuf:"varint,2,opt,name=nbyte" json:"nbyte,omitempty"`
}

func (m *SizeMetaReply) Reset()                    { *m = SizeMetaReply{} }
func (m *SizeMetaReply) String() string            { return proto.CompactTextString(m) }
func (*SizeMetaReply) ProtoMessage()               {}
func (*SizeMetaReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *SizeMetaReply) GetNrow() int64 {
	if m != nil {
		return m.Nrow
	}
	return 0
}

func (m *SizeMetaReply) GetNbyte() int64 {
	if m != nil {
		return m.Nbyte
	}
	return 0
}

type PluginSizeMetaReply struct {
	Errcode  int32          `protobuf:"varint,1,opt,name=errcode" json:"errcode,omitempty"`
	Errmsg   string         `protobuf:"bytes,2,opt,name=errmsg" json:"errmsg,omitempty"`
	Sizemeta *SizeMetaReply `protobuf:"bytes,3,opt,name=sizemeta" json:"sizemeta,omitempty"`
}

func (m *PluginSizeMetaReply) Reset()                    { *m = PluginSizeMetaReply{} }
func (m *PluginSizeMetaReply) String() string            { return proto.CompactTextString(m) }
func (*PluginSizeMetaReply) ProtoMessage()               {}
func (*PluginSizeMetaReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *PluginSizeMetaReply) GetErrcode() int32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *PluginSizeMetaReply) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *PluginSizeMetaReply) GetSizemeta() *SizeMetaReply {
	if m != nil {
		return m.Sizemeta
	}
	return nil
}

// one note on WriteRequest.
// Suppose we are writing 2 columns:
// Message 1: must have filespec and columndesc, and no data
// Message 2: data only, 4 byte length of page 1 (page of column 1)
// Message 3..n: data only, page 1 in 16kb chunks
// Message n+1: data only, 4 byte length of page 2 (page of column 2)
// Message n+2..m: data only, page 2 in 16kb chunks
// Message m+1: data only, 4 byte length of page 1  (another page of column 1)
// Message m+1 .. k: dat only, page 1 in 16kb chunks
// ...
type WriteRequest struct {
	Filespec   *FileSpec     `protobuf:"bytes,1,opt,name=filespec" json:"filespec,omitempty"`
	Columndesc []*ColumnDesc `protobuf:"bytes,2,rep,name=columndesc" json:"columndesc,omitempty"`
	Data       []byte        `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	FragId     int32         `protobuf:"varint,4,opt,name=frag_id,json=fragId" json:"frag_id,omitempty"`
	FragCnt    int32         `protobuf:"varint,5,opt,name=frag_cnt,json=fragCnt" json:"frag_cnt,omitempty"`
}

func (m *WriteRequest) Reset()                    { *m = WriteRequest{} }
func (m *WriteRequest) String() string            { return proto.CompactTextString(m) }
func (*WriteRequest) ProtoMessage()               {}
func (*WriteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *WriteRequest) GetFilespec() *FileSpec {
	if m != nil {
		return m.Filespec
	}
	return nil
}

func (m *WriteRequest) GetColumndesc() []*ColumnDesc {
	if m != nil {
		return m.Columndesc
	}
	return nil
}

func (m *WriteRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *WriteRequest) GetFragId() int32 {
	if m != nil {
		return m.FragId
	}
	return 0
}

func (m *WriteRequest) GetFragCnt() int32 {
	if m != nil {
		return m.FragCnt
	}
	return 0
}

type PluginWriteRequest struct {
	Filespec   *FileSpec     `protobuf:"bytes,1,opt,name=filespec" json:"filespec,omitempty"`
	Columndesc []*ColumnDesc `protobuf:"bytes,2,rep,name=columndesc" json:"columndesc,omitempty"`
	Rowset     *XRowSet      `protobuf:"bytes,3,opt,name=rowset" json:"rowset,omitempty"`
}

func (m *PluginWriteRequest) Reset()                    { *m = PluginWriteRequest{} }
func (m *PluginWriteRequest) String() string            { return proto.CompactTextString(m) }
func (*PluginWriteRequest) ProtoMessage()               {}
func (*PluginWriteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *PluginWriteRequest) GetFilespec() *FileSpec {
	if m != nil {
		return m.Filespec
	}
	return nil
}

func (m *PluginWriteRequest) GetColumndesc() []*ColumnDesc {
	if m != nil {
		return m.Columndesc
	}
	return nil
}

func (m *PluginWriteRequest) GetRowset() *XRowSet {
	if m != nil {
		return m.Rowset
	}
	return nil
}

type WriteReply struct {
}

func (m *WriteReply) Reset()                    { *m = WriteReply{} }
func (m *WriteReply) String() string            { return proto.CompactTextString(m) }
func (*WriteReply) ProtoMessage()               {}
func (*WriteReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

type PluginWriteReply struct {
	Errcode int32  `protobuf:"varint,1,opt,name=errcode" json:"errcode,omitempty"`
	Errmsg  string `protobuf:"bytes,2,opt,name=errmsg" json:"errmsg,omitempty"`
}

func (m *PluginWriteReply) Reset()                    { *m = PluginWriteReply{} }
func (m *PluginWriteReply) String() string            { return proto.CompactTextString(m) }
func (*PluginWriteReply) ProtoMessage()               {}
func (*PluginWriteReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *PluginWriteReply) GetErrcode() int32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *PluginWriteReply) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

type XMsg struct {
	Name   string        `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Xflag  XMsg_XMsgFlag `protobuf:"varint,2,opt,name=xflag,enum=xdrive.XMsg_XMsgFlag" json:"xflag,omitempty"`
	Code   int32         `protobuf:"varint,3,opt,name=code" json:"code,omitempty"`
	Info   string        `protobuf:"bytes,4,opt,name=info" json:"info,omitempty"`
	Rowset *XRowSet      `protobuf:"bytes,5,opt,name=rowset" json:"rowset,omitempty"`
}

func (m *XMsg) Reset()                    { *m = XMsg{} }
func (m *XMsg) String() string            { return proto.CompactTextString(m) }
func (*XMsg) ProtoMessage()               {}
func (*XMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *XMsg) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *XMsg) GetXflag() XMsg_XMsgFlag {
	if m != nil {
		return m.Xflag
	}
	return XMsg_EOS
}

func (m *XMsg) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *XMsg) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *XMsg) GetRowset() *XRowSet {
	if m != nil {
		return m.Rowset
	}
	return nil
}

func init() {
	proto.RegisterType((*ColumnDesc)(nil), "xdrive.ColumnDesc")
	proto.RegisterType((*Filter)(nil), "xdrive.Filter")
	proto.RegisterType((*CSVSpec)(nil), "xdrive.CSVSpec")
	proto.RegisterType((*FileSpec)(nil), "xdrive.FileSpec")
	proto.RegisterType((*StringList)(nil), "xdrive.StringList")
	proto.RegisterType((*KeyValue)(nil), "xdrive.KeyValue")
	proto.RegisterType((*KeyValueList)(nil), "xdrive.KeyValueList")
	proto.RegisterType((*RmgrInfo)(nil), "xdrive.RmgrInfo")
	proto.RegisterType((*ReadRequest)(nil), "xdrive.ReadRequest")
	proto.RegisterType((*SampleRequest)(nil), "xdrive.SampleRequest")
	proto.RegisterType((*DataReply)(nil), "xdrive.DataReply")
	proto.RegisterType((*XCol)(nil), "xdrive.XCol")
	proto.RegisterType((*XRowSet)(nil), "xdrive.XRowSet")
	proto.RegisterType((*PluginDataReply)(nil), "xdrive.PluginDataReply")
	proto.RegisterType((*SizeMetaRequest)(nil), "xdrive.SizeMetaRequest")
	proto.RegisterType((*SizeMetaReply)(nil), "xdrive.SizeMetaReply")
	proto.RegisterType((*PluginSizeMetaReply)(nil), "xdrive.PluginSizeMetaReply")
	proto.RegisterType((*WriteRequest)(nil), "xdrive.WriteRequest")
	proto.RegisterType((*PluginWriteRequest)(nil), "xdrive.PluginWriteRequest")
	proto.RegisterType((*WriteReply)(nil), "xdrive.WriteReply")
	proto.RegisterType((*PluginWriteReply)(nil), "xdrive.PluginWriteReply")
	proto.RegisterType((*XMsg)(nil), "xdrive.XMsg")
	proto.RegisterEnum("xdrive.SpqType", SpqType_name, SpqType_value)
	proto.RegisterEnum("xdrive.XMsg_XMsgFlag", XMsg_XMsgFlag_name, XMsg_XMsgFlag_value)
}

func init() { proto.RegisterFile("xdrive_data.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xcc, 0x56, 0x5b, 0x8f, 0xdb, 0x44,
	0x14, 0xae, 0xe3, 0x6b, 0x4e, 0xd2, 0xd6, 0x1d, 0x96, 0x62, 0x10, 0x2a, 0x91, 0x1f, 0x4a, 0xb8,
	0x68, 0x45, 0xd3, 0xd5, 0x0a, 0x1e, 0x77, 0x93, 0xac, 0x14, 0x9a, 0x4d, 0xca, 0x38, 0xbd, 0x3d,
	0x55, 0xae, 0x33, 0x49, 0xad, 0x3a, 0xb6, 0xd7, 0x76, 0xb2, 0xcd, 0x3e, 0xad, 0x54, 0x24, 0xc4,
	0xaf, 0xe0, 0x91, 0xbf, 0x00, 0x7f, 0x01, 0xf1, 0x43, 0xb8, 0x3c, 0xf2, 0x07, 0xd0, 0x1c, 0xcf,
	0xe4, 0xb2, 0x62, 0x11, 0xf0, 0xb0, 0xe2, 0x25, 0x3a, 0xdf, 0x39, 0x67, 0xce, 0xe5, 0x9b, 0x73,
	0x26, 0x86, 0x5b, 0xaf, 0xc7, 0x59, 0xb8, 0x60, 0xcf, 0xc7, 0x7e, 0xe1, 0xef, 0xa6, 0x59, 0x52,
	0x24, 0xc4, 0x28, 0x55, 0xee, 0x1e, 0x40, 0x3b, 0x89, 0xe6, 0xb3, 0xb8, 0xc3, 0xf2, 0x80, 0x10,
	0xd0, 0x62, 0x7f, 0xc6, 0x1c, 0xa5, 0xa1, 0x34, 0xab, 0x14, 0x65, 0xae, 0x2b, 0x96, 0x29, 0x73,
	0x2a, 0x0d, 0xa5, 0xa9, 0x53, 0x94, 0xdd, 0x0e, 0x18, 0x47, 0x61, 0x54, 0xb0, 0x8c, 0xdc, 0x80,
	0x4a, 0x92, 0x0a, 0xff, 0x4a, 0x92, 0x92, 0xdb, 0x60, 0x04, 0x18, 0x0f, 0xfd, 0xab, 0x54, 0x20,
	0x1e, 0xc5, 0xcf, 0xa6, 0xb9, 0xa3, 0x36, 0x54, 0x1e, 0x99, 0xcb, 0xee, 0x37, 0x0a, 0x98, 0x6d,
	0xef, 0xb1, 0x97, 0xb2, 0x80, 0xbc, 0x0f, 0xd5, 0x31, 0x8b, 0xc2, 0x59, 0x58, 0xb0, 0x4c, 0x84,
	0x5b, 0x2b, 0x88, 0x03, 0x66, 0x3c, 0x8f, 0xa2, 0xbc, 0xc8, 0x44, 0x58, 0x09, 0x79, 0xbe, 0x97,
	0xcc, 0x1f, 0xb3, 0xcc, 0x51, 0x1b, 0x4a, 0xd3, 0xa2, 0x02, 0x91, 0x1d, 0xd0, 0x4f, 0xe6, 0x49,
	0xc1, 0x1c, 0x0d, 0xfd, 0x4b, 0xc0, 0xbd, 0x59, 0x1e, 0xf8, 0x29, 0x73, 0xf4, 0xb2, 0xba, 0x12,
	0xb9, 0x3e, 0x58, 0x47, 0x61, 0xc4, 0xb0, 0x12, 0x02, 0x5a, 0xea, 0x17, 0x2f, 0x25, 0x07, 0x5c,
	0xe6, 0xe7, 0x26, 0x49, 0x36, 0xf3, 0x0b, 0xd9, 0x55, 0x89, 0xc8, 0x47, 0x60, 0x06, 0xf9, 0x22,
	0x4f, 0x59, 0x80, 0xe9, 0x6b, 0xad, 0x9b, 0xbb, 0x25, 0xaf, 0xbb, 0xa2, 0x2f, 0x2a, 0xed, 0xee,
	0x1d, 0x00, 0xaf, 0xc8, 0xc2, 0x78, 0xda, 0x0f, 0xf3, 0x82, 0xd8, 0xa0, 0xf2, 0x66, 0x14, 0x64,
	0x83, 0x8b, 0x6e, 0x0b, 0xac, 0x07, 0x6c, 0xf9, 0xd8, 0x8f, 0xe6, 0x8c, 0x5b, 0x5f, 0xb1, 0xa5,
	0xa8, 0x80, 0x8b, 0xbc, 0x9d, 0x05, 0x37, 0x89, 0xfc, 0x25, 0x70, 0x3f, 0x83, 0xba, 0x3c, 0x83,
	0x51, 0x1b, 0x50, 0x79, 0xb5, 0xc0, 0xa0, 0xb5, 0x96, 0x2d, 0x2b, 0x91, 0x1e, 0xb4, 0xf2, 0x6a,
	0xe1, 0xfe, 0xa4, 0x80, 0x45, 0x67, 0xd3, 0xac, 0x17, 0x4f, 0x12, 0xde, 0x55, 0x1e, 0xbc, 0x64,
	0xab, 0xfb, 0x16, 0xe8, 0xd2, 0x6e, 0x77, 0x40, 0xcf, 0x90, 0x1a, 0xb5, 0x2c, 0x02, 0x01, 0x69,
	0x82, 0x16, 0x24, 0xf1, 0x04, 0x89, 0xae, 0xb5, 0x76, 0x2e, 0xa6, 0xe5, 0x85, 0x51, 0xf4, 0x20,
	0xef, 0x81, 0x95, 0x46, 0xf3, 0x69, 0x18, 0x27, 0xa9, 0xe0, 0x7f, 0x85, 0xc9, 0x3b, 0x60, 0x4e,
	0x32, 0x7f, 0xfa, 0x3c, 0x1c, 0x3b, 0x06, 0x0e, 0x9a, 0xc1, 0x61, 0x6f, 0x4c, 0xde, 0x05, 0x0b,
	0x0d, 0x41, 0x5c, 0x38, 0x26, 0x5a, 0xd0, 0xb1, 0x1d, 0x17, 0xee, 0xef, 0x0a, 0xd4, 0x28, 0xf3,
	0xc7, 0x94, 0x9d, 0xcc, 0x59, 0x5e, 0x90, 0x4f, 0xc1, 0x9a, 0x84, 0x11, 0xc3, 0xeb, 0x50, 0xb0,
	0x9a, 0x15, 0x09, 0xf2, 0x76, 0xe9, 0xca, 0x83, 0xb4, 0x00, 0xca, 0xd9, 0x1c, 0xb3, 0x3c, 0x70,
	0x2a, 0x48, 0x1a, 0x59, 0x5d, 0xdf, 0x6a, 0x27, 0xe8, 0x86, 0x17, 0xb9, 0x23, 0xcf, 0x44, 0x61,
	0x5e, 0x88, 0x59, 0xde, 0xd0, 0x90, 0xbb, 0x60, 0x4c, 0x70, 0x2f, 0x1c, 0x0d, 0xe3, 0xdd, 0xd8,
	0xc8, 0x5f, 0xb0, 0x8c, 0x0a, 0xeb, 0x66, 0xb7, 0xfa, 0xa5, 0xdd, 0x1a, 0xdb, 0xdd, 0xfe, 0xa8,
	0xc0, 0x75, 0xcf, 0x9f, 0xa5, 0x11, 0xbb, 0xba, 0x7e, 0x37, 0xea, 0x54, 0x2f, 0xad, 0x53, 0xdb,
	0xaa, 0x13, 0xdf, 0x90, 0x2c, 0x39, 0x15, 0x8d, 0xa1, 0xec, 0x7e, 0x00, 0xd5, 0x8e, 0x5f, 0xf8,
	0x94, 0xa5, 0xd1, 0x92, 0x3b, 0xf0, 0x87, 0x08, 0x4b, 0xae, 0x53, 0x94, 0xdd, 0x9f, 0x15, 0xd0,
	0x9e, 0xb6, 0x93, 0x88, 0x6f, 0x7a, 0x90, 0x44, 0x1b, 0x8f, 0x90, 0x84, 0xab, 0xb8, 0x95, 0x75,
	0x5c, 0xf9, 0x2e, 0xcc, 0xfc, 0x14, 0x2f, 0xc3, 0xa2, 0x12, 0xf2, 0x59, 0xcd, 0x31, 0x8b, 0x86,
	0x97, 0x54, 0x02, 0xee, 0x1f, 0xde, 0x6f, 0xa1, 0x5e, 0x6f, 0xa8, 0xbc, 0x6a, 0x01, 0xd1, 0xb2,
	0xbf, 0x87, 0x16, 0xa3, 0xa1, 0x36, 0x55, 0x2a, 0x21, 0xb7, 0x4c, 0xc4, 0x19, 0xb3, 0xa1, 0x36,
	0x2b, 0x54, 0x42, 0xb4, 0x88, 0x33, 0x56, 0x43, 0x6d, 0x2a, 0x54, 0x42, 0xf7, 0x19, 0x98, 0x4f,
	0x69, 0x72, 0xea, 0x31, 0xdc, 0xf4, 0xc2, 0x9f, 0x62, 0x33, 0x3a, 0xe5, 0x22, 0xae, 0x51, 0x32,
	0x8f, 0xc7, 0xa2, 0x93, 0x12, 0x90, 0xbb, 0xd8, 0xf8, 0x7c, 0x16, 0x97, 0x6f, 0x64, 0xad, 0x55,
	0x97, 0x77, 0xc3, 0x79, 0xa1, 0xd2, 0xe8, 0x46, 0x70, 0xf3, 0x21, 0x2e, 0xcd, 0x9a, 0x50, 0x07,
	0x4c, 0x96, 0x65, 0x41, 0x32, 0x66, 0x22, 0x8d, 0x84, 0xf8, 0xde, 0x65, 0xd9, 0x2c, 0x9f, 0xca,
	0x4d, 0x2e, 0x11, 0xf9, 0x10, 0x8c, 0x2c, 0x39, 0xcd, 0x59, 0x71, 0xf1, 0xd9, 0x12, 0x55, 0x53,
	0x61, 0x76, 0xbf, 0x57, 0xe0, 0xa6, 0x17, 0x9e, 0xb1, 0x63, 0xc6, 0x93, 0xfd, 0x8f, 0xc7, 0xce,
	0xfd, 0x02, 0xae, 0xaf, 0x0b, 0x15, 0x63, 0x86, 0xf3, 0xc2, 0x4b, 0x54, 0xc5, 0xbc, 0xec, 0x80,
	0x1e, 0xbf, 0x58, 0x16, 0xe5, 0x33, 0xaa, 0xd2, 0x12, 0xb8, 0x67, 0xf0, 0x56, 0x49, 0xe9, 0x76,
	0x80, 0x7f, 0x4f, 0xeb, 0x3d, 0xb0, 0xf2, 0xf0, 0x8c, 0xcd, 0x58, 0xe1, 0x0b, 0x62, 0xdf, 0x96,
	0x9d, 0x6e, 0x85, 0xa6, 0x2b, 0x37, 0xf7, 0x07, 0x05, 0xea, 0x4f, 0xb2, 0xb0, 0xb8, 0xc2, 0xa5,
	0x96, 0xfb, 0xa7, 0xae, 0xf7, 0x6f, 0x93, 0x71, 0xed, 0x52, 0xc6, 0xf5, 0x6d, 0xc6, 0xbf, 0x53,
	0x80, 0x94, 0xbc, 0x5d, 0x71, 0x03, 0xff, 0x78, 0x7a, 0xeb, 0x00, 0xa2, 0xb4, 0x34, 0x5a, 0xba,
	0x1d, 0xb0, 0xb7, 0xca, 0xfd, 0x4f, 0x77, 0xcc, 0xff, 0x74, 0xb4, 0xa7, 0xc7, 0xf9, 0xf4, 0x2f,
	0xbf, 0x95, 0x3e, 0x01, 0xfd, 0xf5, 0x24, 0xf2, 0xcb, 0x33, 0x37, 0xd6, 0xb7, 0xcf, 0x0f, 0xe0,
	0xcf, 0x51, 0xe4, 0x4f, 0x69, 0xe9, 0xc3, 0x03, 0x60, 0xe2, 0x72, 0xc4, 0x51, 0xe6, 0xba, 0x30,
	0x9e, 0x24, 0xe2, 0xab, 0x05, 0xe5, 0x8d, 0x76, 0xf5, 0xbf, 0x6f, 0xf7, 0x2b, 0xb0, 0x64, 0x0e,
	0x62, 0x82, 0xda, 0x1d, 0x7a, 0xf6, 0xb5, 0x52, 0x38, 0xb4, 0x15, 0x52, 0x07, 0xab, 0x3d, 0x1c,
	0x8c, 0x7a, 0x83, 0x47, 0x5d, 0xbb, 0x42, 0xaa, 0xa0, 0x79, 0xcf, 0x06, 0x6d, 0xfb, 0x17, 0x93,
	0xd4, 0xc1, 0x3c, 0xf4, 0x1e, 0x22, 0xfa, 0x55, 0xa2, 0xce, 0xc1, 0xe8, 0xc0, 0xfe, 0xcd, 0xfc,
	0xf8, 0x0f, 0x05, 0x4c, 0x2f, 0x3d, 0x19, 0x2d, 0x53, 0x46, 0x6a, 0x60, 0x3e, 0x1a, 0x3c, 0x18,
	0x0c, 0x9f, 0x0c, 0xec, 0x6b, 0xc4, 0x02, 0xed, 0x70, 0x38, 0xec, 0xdb, 0x0a, 0xa9, 0x82, 0xde,
	0x1b, 0x8c, 0xee, 0xed, 0x63, 0x50, 0x2e, 0xde, 0x6f, 0xd9, 0xaa, 0x10, 0xf7, 0xf7, 0x6c, 0x8d,
	0x00, 0x18, 0xdc, 0xa1, 0xf5, 0xb9, 0xad, 0x73, 0xf5, 0x51, 0x7f, 0x78, 0x30, 0xb2, 0x0d, 0xae,
	0xee, 0x0c, 0x1f, 0x1d, 0xf6, 0xbb, 0xb6, 0xc9, 0xa3, 0xb5, 0xbd, 0x11, 0xb5, 0xab, 0xdc, 0xa1,
	0xd3, 0x6d, 0xef, 0xef, 0xd9, 0x80, 0x0e, 0xdd, 0x36, 0x3f, 0x57, 0x23, 0x00, 0x5a, 0xe7, 0x60,
	0xd4, 0xb5, 0xdf, 0x9c, 0x6b, 0xe4, 0x16, 0xd4, 0x46, 0xbd, 0xe3, 0xee, 0xf3, 0xe3, 0x5e, 0xbf,
	0xdf, 0xf3, 0xec, 0x37, 0xe7, 0x16, 0xb9, 0x0d, 0x36, 0x57, 0x79, 0xa3, 0x83, 0xe3, 0x87, 0x52,
	0xff, 0xf5, 0x79, 0x7d, 0xc3, 0xb5, 0x4d, 0x87, 0x5c, 0x65, 0x5f, 0x74, 0x15, 0xfa, 0x1d, 0x9e,
	0xe1, 0x4b, 0x6f, 0x38, 0xb0, 0xbf, 0x3d, 0x77, 0x0e, 0x1d, 0xb8, 0x1d, 0x24, 0xb3, 0xdd, 0x45,
	0x58, 0xb0, 0x3c, 0x67, 0xf8, 0xd5, 0x5c, 0x52, 0xfe, 0xc2, 0xc0, 0xaf, 0xe7, 0xfb, 0x7f, 0x06,
	0x00, 0x00, 0xff, 0xff, 0xf9, 0x8b, 0x79, 0x09, 0x52, 0x0b, 0x00, 0x00,
}
